### ISSUE TITLE
Refactor login page

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#101]
At the moment, the login page has a couple of minor problems:

- ~error messages from the server are not shown (the provider is refreshed)~
- after logging in, the screen "flickers" a bit because we show a different screen while waiting for the response for the server
- due to #100, while the application checks whether it is compatible with the server, it loads the home screen, which triggers all the request which could potentially fail

## Proposal

We should implement the following workflow:

- The user tries to login, while we wait for the request to return, the login button is disabled and shows a spinner. Any errors that are returned by the server are shown to the user. We can use the existing error dialogs, no need to reinvent the wheel.
- If the login was successfull, check for app compatibility (keeping the spinner in the button is probably a good idea) and if the check fails, show the update app screen.
- Everything is OK, show the dashboard and proceed as normal

To do this we probably need to refactor the auth provider.

**Comment by AmanNegi** [comment]
Hey @rolandgeider can I work on this issue?

**Comment by rolandgeider** [comment]
it's yours
