### ISSUE TITLE
Problem building app for android 12

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [wger-project/flutter#119]
wger was recently published on fdroid - 
https://f-droid.org/packages/de.wger.flutter/

with my "lenovo tab android 9 go" i can install and launch the app normally.

But with my "Samsung S21 5G Android 12" I can't install wger, it always gives me the following error message (see screenshot):

Parsing apk file failed!Maybe minSdk of apk is smaller than actual sdk? Look in logcat for more precise warnings from Android's PackageParser
![wgerproblem](https://user-images.githubusercontent.com/61406324/146821184-a7ca9cb3-c964-4cfb-8018-de5f2a382a6e.jpeg)

**Comment by rolandgeider** [comment]
Issue was fixed with #123
