### ISSUE TITLE
Add dynamic translations

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#120]
At the moment a handful of strings can't be translated, since they come as a response from the server and can't be translated directly with flutter. All of them (I think) are stored in the database and don't change much if ever (things like units, or category names)

Todo:
- extend the i18n extract script we already have on the server side to write a dummy .dart file with the contents
- copy this file over to this repo so the strings are picked up
- add a utility function that machtes the string and returns the translation (basically a big switch statement)

**Comment by memoriasIT** [comment]
Wouldn't it be better to supply a locale field in the request to get the correct language and then in backend implement localization?
Btw, I am a native spanish speaker and I might be able to help to translate/correct the Spanish translations :)

**Comment by rolandgeider** [comment]
that would be a possibility, but would need some changes on the backend as well (e.g. at the moment for things like categories we just read out the data from the database/api and we'd need to add a translation layer there as well), also the flutter app is translated into some languages that the webapp isn't (and vice versa) so we might get a mismatch there as well.

In the end, it's probably easier to just translate the categories, equipment, etc. here as well since they haven't changed in years :)

**Comment by rolandgeider** [comment]
and any corrections etc. to the existing translations are of course always welcome
