### ISSUE TITLE
APP language or translation

### ISSUE THREAD

**Issue by nmfreitas** [wger-project/flutter#127]
Hi, before talking about my isseu i want to thank for the awosome work you guys are doing! Excelente app!
OK, now my isseu. 

I instaled the APP via play store version 1.4.1 and F-Droid version 1.4.0 and both come without full english. (See prints) and i cant see an option to chance or translate. 

Can someone help? 

![Screenshot_20220201_144626_de wger flutter](https://user-images.githubusercontent.com/86863705/151990258-0c78f4a0-4aff-4d63-9ba4-f55805da6e76.jpg)
![Screenshot_20220201_144044_de wger flutter](https://user-images.githubusercontent.com/86863705/151989985-6ce26358-eee1-4ac7-a6e0-c93c3f58546a.jpg)
![Screenshot_20220201_144630_de wger flutter](https://user-images.githubusercontent.com/86863705/151990244-1a8303c5-0e2f-4f45-b51c-a2a00010aeb7.jpg)

**Comment by rolandgeider** [comment]
Hi! This seems to be a bug in flutter where sometimes it ignores the system language and simply takes the first translation, which in this case is Amharic... (I myself have never encountered this) There is probably little we can do till the flutter guys fix it, we don't do anything with the locale, just use the system language if there is a translation for it.

**Comment by Lrss** [comment]
It would be useful to have a language switcher on the login page, so you could easily change it to your preferred language on the first page you are presented with.

**Comment by rolandgeider** [comment]
I think android 12 or 13 allows the user to set the language on a per app basis, but that is slightly cumbersome UI wise and nobody knows about it

If somebody wants to contribute such a switcher (also having it in the preferences page would make sense), go ahead

**Comment by rolandgeider** [comment]
Added a workaround for this so the fallback language is English
