### ISSUE TITLE
Gallery not refreshing after actions

### ISSUE THREAD

**Issue by dugite-code** [wger-project/flutter#128]
## Steps to Reproduce

1. ... Add image to gallery (Or delete an existing image)
2. ... Select Choose from photo library or take image
3. ... Upload file

**Expected results:**
Gallery view should re-fresh and display the newest image

**Actual results:**
Gallery view remains displaying old images until app is fully exited and opened again

Device details:
Motorola One vision Android 11
wger app version 1.4.1

Perhaps a pull to refresh function may be useful as a feature request?

**Comment by rolandgeider** [comment]
Thanks for reporting this, you are right!

BTW it seems it's enough to switch to another tab and then go back but that's of course still a workaround. We'll probably forgot to refresh the gallery provider or something like that

**Comment by rolandgeider** [comment]
This is fixed but can't say yet when we will publish a new version
