### ISSUE TITLE
add support for popular workout plans for new users to choose from 

### ISSUE THREAD

**Issue by liang799** [wger-project/flutter#131]
## Use case

As a new user who is new to fitness and this app, I find it troublesome to search online for a workout plan and manually copying and pasting each of the exercise name into the app.
## Proposal

I would like wger to be able to display some popular workout plans that new users like me can choose.

The popular workout plans should ideally be context sensitive, i.e. only visible to new users, and new users should be able to add the selected workout plan to their list of workout plans.

**Comment by rolandgeider** [comment]
Hi! The idea behind wger was that it would be very unopinionated and would not try to calculate stuff or make any plans for you. That being said, once we implement things like https://github.com/wger-project/wger/issues/848, we should provide at least some basic routines that users could use.

At the moment there are some publicly available routine templates provided by the community (on the web app only atm)

**Comment by liang799** [comment]
Thank you for the clarification
