### ISSUE TITLE
Add masonry type interface to gallery

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#150]
Having a masonry type of interface in the gallery would probably be an improvement, at the moment the pictures are shown as squares and details at the top and bottom are cut out. We could try adding a [staggered grid view](https://pub.dev/packages/flutter_staggered_grid_view) and see if it really is an improvement

**Comment by Aaliya-Ali** [comment]
Hello, 
I'd like to give this issue a try, let me know if it has been taken already. Also wanted to know if this issue is a part of hacktoberfest. I am new to open source, please guide me on how to get started.

**Comment by rolandgeider** [comment]
Hi @Aaliya-Ali !

yeah, this repo is participating in hacktoberfest so all issues/PRs count. You can use the test server as a backend then you don't need to setup anything (the DB is reset every day) and there should enough images to see if the masonry is an improvement:

https://wger-master.rge.uber.space/ (click on "custom server" in the login page)
Username: user
Password: flutteruser

Have you worked with git and forks and so on before?

**Comment by rolandgeider** [comment]
BTW, we expose the image's height and width over the API but currently don't read it or do anything with it, in case you need the information to decide how to display the images

**Comment by Aaliya-Ali** [comment]
Hey @rolandgeider,
Thanks for all the information! I'll try running the app locally and will let you know in case of any problems. And yes, I have some experience working with git.

**Comment by Aaliya-Ali** [comment]
Hello, 
As suggested, I used the flutter_staggered_grid_view package and managed to replace the GridView with a MasonryGridView. Are there any other changes you'd like me to make? Attaching a screenshot for your reference.

<img width="341" alt="image" src="https://user-images.githubusercontent.com/63385197/193421183-6ac2f0bb-8dd8-4c17-afef-bb5b7fed81ce.png">

**Comment by rolandgeider** [comment]
That looks great!

**Comment by Aaliya-Ali** [comment]
Hello,
It seems like a few tests on my PR failed, is there anything I need to do? Actually, I've never worked with tests before.

**Comment by rolandgeider** [comment]
you are right, I'll take a look later today, we're probably checking for the old card widgets which can't be found anymore or something similar

**Comment by rolandgeider** [comment]
I don't really know why the tests only find 2 widgets, instead of the four that should be there, it's a bit strange, I'll keep looking

**Comment by Aaliya-Ali** [comment]
Same here, I tried finding out but could not understand either. Can you tell me a bit more about the 4 widgets the test is looking for?

**Comment by rolandgeider** [comment]
So if you look into `gallery_screen_test.dart` you see that in setup() we mock the gallery provider. This means that we fake tcertain responses so that we can run the tests without the need for any backend, database or any external services. In this case we simply return `getTestImages()` which is a list with four images.

Then we render the gallery with that provider and basically check that there are four widgets of the type GestureDetector (so basically that we rendered what we thought would render). Now that I think about it, there might be a better way to make the images clickable, but that doesn't answer our question

**Comment by Aaliya-Ali** [comment]
Got it, thanks for the clarification! I'll try to find a fix.

**Comment by rolandgeider** [comment]
I have tried adding a `await tester.pumpAndSettle();` which is needed e.g. when there are animations or such and we need to wait till they are over till we check if certain elements are visible in the widget tree, but this also didn't work. I will try to get somehow a screenshot out of the tests to see what is happening.

While tests are incredibly useful and have saved my ass a lot of times and I can only recommend writing them, sometimes they break for seemingly no reason 🤷🏻‍♂️

**Comment by rolandgeider** [comment]
I mean, it finds two of them, so it can't be too wrong. But yes, it has to have something to do with it

**Comment by Aaliya-Ali** [comment]
@rolandgeider I modified the tests(added a test for ```SliverMasonryGrid``` and set the ```skipOffstage``` to false for ```GestureDetector```) and all the tests passed successfully.
<img width="933" alt="image" src="https://user-images.githubusercontent.com/63385197/196625051-f5c8df05-7a59-49aa-be7c-1cd0edc6c4a9.png">
Tests work even if line 61 is removed.

Do you think the problem is fixed and would you like me to push the changes?

**Comment by rolandgeider** [comment]
cool! yes, that definitely fixes it
