### ISSUE TITLE
Remove dependency on Google Play Services

### ISSUE THREAD

**Issue by linsui** [wger-project/flutter#152]
GMS is pulled in the apk by flutter_barcode_scanner. See https://github.com/AmolGangadhare/flutter_barcode_scanner/blob/c466d32d017c29cd34307b5681f697891c55babc/android/build.gradle#L41. Could you please take a look? Thanks!

**Comment by rolandgeider** [comment]
oh you are right! Do you know of some other barcode scanner for flutter that doesn't depend on the play services?

**Comment by linsui** [comment]
I don't know. It seems there is no other flutter barcode scanner on F-Droid. But maybe you can try https://github.com/juliuscanute/qr_code_scanner and https://github.com/leyan95/qrcode_scanner.

**Comment by rolandgeider** [comment]
alright, I'll take a look

**Comment by rolandgeider** [comment]
Mhhh the other scanner apps that I have found have a dependency on Google's MLkit, which is also not FOSS

**Comment by linsui** [comment]
https://github.com/juliuscanute/qr_code_scanner is used in some other apps in F-Droid.

**Comment by rolandgeider** [comment]
That one is sadly not maintained anymore. I guess it would be better than nothing, but it still has a "bad taste"

**Comment by linsui** [comment]
Since the zxing is not maintained either we don't have too much choice.

**Comment by rolandgeider** [comment]
I guess we don't... grrrr

**Comment by gargchirayu** [comment]
Is this issue resolved or still needs work? If this is a hacktoberfest issue i would like to work on it please.

**Comment by rolandgeider** [comment]
Hi! Yes this issue is not only still open and is part of hacktobest, it would be really useful if it would be done.

**Comment by tavkeer** [comment]
hi is this issue resolved or still needs word!
i would like to contribute to it

**Comment by roshavagarga** [comment]
Wouldn't this version of zxing be an option? https://github.com/zxing-cpp/zxing-cpp

**Comment by rolandgeider** [comment]
that looks promising, thanks @roshavagarga

**Comment by MrRulf** [comment]
I found this one, but I can't tell if it has dependencies on gms core or something, in the metadata for dependencies those looked quite "normal"

**Comment by MrRulf** [comment]
If the only thing that's needed is the Google Vision API for barcodes people with microg should be fine. 
iirc it's also possible to have apps on fdroid with dependencies on not free services, like the play services, or free alternatives, like microg. 

I know it does not solve the problem, but this way the version from fdroid stays usable, since there are incompatibilities from 1.4.3 (fdroid) with the latest server. 
Also, technically people without play services and fdroid should be able to use the app anyway, just not the barcode scanner.

**Comment by rolandgeider** [comment]
Hey! Yes, the application is usable without the play services till the user clicks on the scan button. When we published the last update it got rejected from fdroid because of the non free dependencies, I'm not sure if we can indicate that we are dependent on them till we replace the library

**Comment by linsui** [comment]
Looks like this problem has been solved! It builds fine but I don't know if it works well. You can test the unsigned apk [here](https://gitlab.com/linsui/fdroiddata/-/jobs/4582019531/artifacts/raw/tmp/de.wger.flutter_33.apk). Since flutter_barcode_scanner has been replaced, why not remove it?

**Comment by artchiee** [comment]
Hi @linsui :: i checked the wger on gitlab , looks like the app failed to build for fdorid check; it's probably still checking for for flutter_barcode_scanner!  so we need to remove it"s trace completely!!

**Comment by linsui** [comment]
I'm not sure whcih check failed. I have removed flutter_barcode_scanner. See https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/de.wger.flutter.yml#L74.

**Comment by artchiee** [comment]
yass saw it ; i also seen this error there "`builds/fdroid/fdroiddata/build/de.wger.flutter/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:29: error: package com.amolg.flutterbarcodescanner does not exist"`
=> from the master branch on github , can explicitly deleting "flutter_bar_code" scanner" from yaml and pub lock files, then rebuild / upload to FDroid , would help !! i'm still seeing the package on master branch  ; since i haven't remove it on my branch when i pushed the Fix :: !

**Comment by linsui** [comment]
It builds in the CI. See https://gitlab.com/linsui/fdroiddata/-/jobs/4582019531#L676.

**Comment by artchiee** [comment]
I might or might not be right about this  , i've had issues with Gradle compatibility in the past  : See => https://gitlab.com/linsui/fdroiddata/-/jobs/4582019531#L2624

**Comment by linsui** [comment]
That's the log of another app.

**Comment by artchiee** [comment]
Hmmm okay !! it's really disturbing since it says "Build Succeeded" and cant build :( ;; w'll look further into this!

**Comment by linsui** [comment]
I'm not sure what you mean. It builds without problem.

**Comment by artchiee** [comment]
soooryy :)) i meant google a bit more if i found smt ; since i dont have permissions to build on Gitlab :) you know we have to get this done -- this issue been open way tooo long !!

**Comment by rolandgeider** [comment]
@artchiee the new version is now in the fdroid metadata repo and will be available as soon as it is built

Closing here (finally)
