### ISSUE TITLE
Save exercises in local database

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#161]
At the moment, the exercises are loaded from the server and the JSON dump saved to local preferences. Among other things, shared_prefs should not be used to store data. It would be better to use something like drift to properly store them in a database which then could be bundled as an asset, further speeding up the startup process (with some kind of update process built on top of this). Since this is a regular sqlite database, it would be perhaps easier/faster to create it on the server and download it on demand.

Having this database would also make it easier for feeel to use the exercise database, but in this case it would be perhaps better medium term to move everything out to a separate package.

Also please note, that having a text field were we simply dump the exercise JSON we get from the server is perfectly ok, then we don't need to add yet another import logic

https://pub.dev/packages/drift
https://gitlab.com/enjoyingfoss/feeel

**Comment by AmanNegi** [comment]
Hey @rolandgeider can I work on this issue. We can use the [flutter_cache_manager](https://pub.dev/packages/flutter_cache_manager) to do this.

**Comment by rolandgeider** [comment]
Hi @AmanNegi ! Sure, this would be really useful for the project

**Comment by rolandgeider** [comment]
You mean as a partial refactoring before moving the stuff to the database?

**Comment by AmanNegi** [comment]
Umm not exactly, what I am suggesting is that we use `shared_prefs` as our database itself. Because I wasn't able to found another viable alternative for it... 

A thing we could do is save the data in a `.json` file in local storage which will store our cache. But then we have to ensure data confidentiality and read/write speeds at our ends.

**Comment by rolandgeider** [comment]
I see what you mean. Yes, moving to a real DB is going to be quite a bit of pain, but we might be able to use some of the code that the developer of feeel is doing in the [drift branch](https://gitlab.com/enjoyingfoss/feeel/-/commits/drift/) later on.

In any case, I agree with you that having everything in one class is much better. I'd suggest moving the discussion to a new issue, so we can keep this one more focused on the db aspect.

**Comment by AmanNegi** [comment]
Okay Sure I'll do that.

**Comment by AmanNegi** [comment]
Hey @rolandgeider, I am really sorry to tell you that I won't be able to work on this issue, due to college and placements. Lots of love to the project 💚
