### ISSUE TITLE
Can't use a wger instance running on a sub-url

### ISSUE THREAD

**Issue by kovdan01** [wger-project/flutter#193]
## Steps to Reproduce

1. Install a wger instance at a sub-url, like https://example.com/wger. I keep in mind that such type of installation is discouraged, but I'm OK with it for my personal usage.
2. Try to login via mobile app.
3. Get `FormatException: Unexpected character (at character 1) <!DOCTYPE HTML PUBLIC ...`.

**Expected results:** 

Successful login.

**Actual results:** 

A FormatException error message.

**Investigation**

I inspected my Apache 2 webserver logs and it turns out that the mobile app just removes sub-url (tries to access `server.name/api/v2/login` instead of `server.name/wger/api/v2/login`) and that's why gets error 404 instead of a json with a response. To fix the problem, we need to alter `makeUri` function (see https://github.com/wger-project/flutter/blob/master/lib/providers/helpers.dart#L20). I'm not a flutter developer, I don't know Dart and I don't have time to setup a development environment, but I suppose that the following fix should work:

```diff
 ]) {
   final Uri uriServer = Uri.parse(serverUrl);
 
-  final pathList = ['api', 'v2', path];
+  final pathList = [uriServer.path, 'api', 'v2', path];
   if (id != null) {
     pathList.add(id.toString());
   }

```

Created a PR https://github.com/wger-project/flutter/pull/192. @rolandgeider Please consider reviewing and merging it. Thanks!

**Comment by rolandgeider** [comment]
Hi! Yes, this is a use case that was never tested, so I'm not surprised it breaks stuff (does the regular web app work fine on a sub path?). I'll try to setup this these days

**Comment by kovdan01** [comment]
> does the regular web app work fine on a sub path?

I was able to login as admin and change password. Did not tested the app extensively, but suppose that everything is OK - at least, I've ensured that links point to correct URLs (including sub-url). The only issue that I have noticed - after login you are redirected to clear domain URL instead of sub-url.

> I'll try to setup this these days

Thanks!

**Comment by rolandgeider** [comment]
Closed with #192

**Comment by gregflynn** [comment]
hate to necro bump but I'm getting this same error but with a subdomain'd server. Web interface works great just can't login to the mobile app. Happy to create a separate issue but wanted to ping here first.

**Comment by rolandgeider** [comment]
hi @gregflynn , a subdomain should make even less problems. What error are you getting?

**Comment by rolandgeider** [comment]
oh wait, you can't login with the mobile app, I think I know what that is

**Comment by gregflynn** [comment]
> hi @gregflynn , a subdomain should make even less problems. What error are you getting?

Same steps to reproduce as this issue with the difference being `https://foo.example.com` as opposed to `https://example.com/foo`

> oh wait, you can't login with the mobile app, I think I know what that is

Awesome, I looked at the PR for resolving this original issue and would have though it would have resolved this subdomain issue too

**Comment by rolandgeider** [comment]
so I think we broke the app login with the new brute force login detection (https://github.com/wger-project/wger/issues/1163), but you can just disable that by setting `AXES_ENABLED=False`

**Comment by gregflynn** [comment]
> so I think we broke the app login with the new brute force login detection ([wger-project/wger#1163](https://github.com/wger-project/wger/issues/1163)), but you can just disable that by setting `AXES_ENABLED=False`

Confirmed! Will take discussion there
