### ISSUE TITLE
Add an option to trust user-install CA certificates for custom instances

### ISSUE THREAD

**Issue by kovdan01** [wger-project/flutter#204]
## Use case

I have installed a wger instance on my server and have issued a certificate for it (to be more precise, there is a chain of certificates: a self-signed root CA cert, an intermediate CA cert and a server cert itself). I have added CA certificate chain to android user CA certificates storage, and now I'm able to access my instance via Bromite browser (with enabled option to trust user-installed certificates). The browser shows a green lock sign and no security warnings, which means that my custom certificate is treated as trusted. The same does not work for wger app - it shows HandshakeException because of certificate verify fail. According to documentation (https://developer.android.com/training/articles/security-config#TrustingAdditionalCas), Android apps targeting API 24 and newer (above Android 6) do not trust user-installed CA certificates by default, but such behavior could be implemented.

## Proposal

As already mentioned, Android web-browsers such as Bromite and Firefox have an option to trust user-installed CA certificated. Would be cool if you implement similar functionality in wger app. Thanks!

**Comment by kovdan01** [comment]
Oh, sorry for opening a duplicate and thanks for such informative reply!

**Comment by rolandgeider** [comment]
Don't worry 😄
