### ISSUE TITLE
Add bar diagram for planned vs logged values

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#21]
We should chart the planned / logged / 7 day average values for energy, protein, carbs, etc. for a nutritional plan. Something like this:

![pattern_forward_hatch_full](https://user-images.githubusercontent.com/2280729/115952754-27adc680-a4e8-11eb-8d1d-e6eb9ee3c973.png)

**Comment by rolandgeider** [comment]
https://google.github.io/charts/flutter/example/bar_charts/pattern_forward_hatch

**Comment by adyhnat** [comment]
Hey guys I would like to work on this, if there will be any difficulties I will write down in a thread

**Comment by adyhnat** [comment]
Hey guys I would like to work on this issue. I will discuss any problems etc in the comments
