### ISSUE TITLE
Custom Exercises

### ISSUE THREAD

**Issue by mrashleyball** [wger-project/flutter#215]
Hi, the ability to add an exercise that isn't in the list/data set would be great. I'm trying to move my PTs routine from another fitness app into wger, but without custom exercises, it's just not possible.

**Comment by rolandgeider** [comment]
Hi! Yeah, making it easier to submit/translate/correct exercises is something we're working on. Everything is basically done, just needs a bit of polishing

**Comment by rolandgeider** [comment]
https://github.com/orgs/wger-project/projects/2

(Closing here)
