### ISSUE TITLE
Exercise full list with filters

### ISSUE THREAD

**Issue by sumugz** [wger-project/flutter#218]
## Use case

Adding an exercise to a plan is really frustrating to search. I have to search for specific things and sometimes people call different names to the same thing or can't remember the specific name of the machine they want to add
## Proposal

Be able to see a full list, a drop-down list isn't working very well. It would be great to be able to filter by the body part/area
We could also add our own excercise. For example it's lacking elliptical training, which also doesn't use kg, so we could add our own parameters

**Comment by rolandgeider** [comment]
Hi! We're actually current reworking how the exercises are handled and among other things, there will be a searchable and filterable overview (also with aliases/alternative names). While I can't say when exactly this will be done, it's pretty complete already.

Closing this to keep the open issues manageable
