### ISSUE TITLE
Add measurements dashboard widget

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#230]
We need a new widget that shows the last measurement entries in the dashboard and allows the user to quickly add new ones (note that it should not be possible to add new categories here, this can be done over the regular view). Since there can be several categories we would need to think of a way to present this to the user in a compact way (perhaps swiping them to the side or something like this)

Ideally we would be able to reuse some of the widgets used in the regular view

![image](https://user-images.githubusercontent.com/2280729/192139802-4d0c478f-5020-4697-a774-9821dd1770c0.png)

**Comment by codereacher15** [comment]
I would like to work on this issue . Can you assign it to me? I am a beginner in open source with little experience pls guide me through the process

**Comment by rolandgeider** [comment]
Hi, this issue is already taken. Would #231 be something for you?

**Comment by codereacher15** [comment]
Yes sure,Would love to work on that

**Comment by bujdy** [comment]
Can you assign this to me?

**Comment by ekakshjanweja** [comment]
@rolandgeider are there any beginner friendly issues available that you can assign to me??

**Comment by Jitender-yaduvanshi** [comment]
Is someone working on this issue now ??
