### ISSUE TITLE
Add User Profile

### ISSUE THREAD

**Issue by skdotv** [wger-project/flutter#244]
## Use case
-> currently in the app user doesn't have a profile section or description of user to see. 
-> User can see his data, update if needed, 
-> User can set profile image, change password from user profile detail screen

## Proposal
- it would be good if we add a drawer with  user profile, name and other features in the list like log out, about. as currently it's showing dialog box to show logout and about option

**Comment by yk3066** [comment]
Do we have to make the frontend of this in flutter? If this is a hacktoberfest issue i would like to take it up

**Comment by rolandgeider** [comment]
Hi @yk3066! Yes this issue is part of hacktoberfest. There is already a UI for some parts of the user profile, but not all fields and not everything is in master yet. Allowing the user to change the password would be very useful

**Comment by SmartAree** [comment]
I would love to work on this issue. Can you please assign this to me?

**Comment by skdotv** [comment]
Hi @rolandgeider, if it’s possible can you assign this ticket to me. 
Also if the password reset api is ready I can work on the reset password functionality and integration in mobile application. 
thank you

**Comment by ekakshjanweja** [comment]
@rolandgeider I think I could work on this issue. Can you assign it to me??

**Comment by antarah** [comment]
Hey, I could be able to add profile section and description as well as data updates and profile page with better UI as I have experience in UI designs of 2 years as well as I have contributed to your issues of landscape mode and  additional chart displaying of nutrition in dashboard. I am well versed with the code. Please assign this issue to me.

**Comment by himanshiiiiii** [comment]
@rolandgeider Plzz can you assign it to me
