### ISSUE TITLE
Alternative to charts_flutter?

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#249]
It seems https://pub.dev/packages/charts_flutter is being discontinued. 

There might be a community driven fork/replacement https://github.com/google/charts/issues/798 but if this doesn't happen, we will need to look for an alternative in the future

**Comment by joaovvrodrigues** [comment]
I found this project on pub.dev, however I don't know who the author is and apparently there is no modification.

[https://pub.dev/packages/charts_flutter_new/changelog](url)

**Comment by joaovvrodrigues** [comment]
I agree with you.

**Comment by Rohit-RA-2020** [comment]
https://pub.dev/packages/syncfusion_flutter_charts
This can be used as a replacement.

**Comment by floodoo** [comment]
Also a good chart package, is the [fl_chart](https://pub.dev/packages/fl_chart) package

**Comment by rolandgeider** [comment]
Sadly the syncfusion package is propietary, but fl_chart might be an alternative worth considering

**Comment by kiocjw** [comment]
Not sure if these consider one of them:
https://github.com/infinum/flutter-charts
https://github.com/entronad/flutter_echarts

**Comment by rolandgeider** [comment]
We're moving with fl charts, branch is linked

**Comment by Vika93Rana** [comment]
What's the issue with proprietary PKG https://pub.dev/packages/syncfusion_flutter_charts

**Comment by rolandgeider** [comment]
It's propietary. And besides that it would hinder us to publish the app to fdroid e.g.

**Comment by artchiee** [comment]
Hi @rolandgeider ; You can go ahead and assign this one to me :) i'll proceed with the fl_chart branch as mentioned above!! Thanks.
