### ISSUE TITLE
Add Theme feature

### ISSUE THREAD

**Issue by trats08** [wger-project/flutter#257]
Dark or Light theme feature will enhance the UI experience of the user. 

Kindly assign me this issue and add the hactoberfest label for the same.

**Comment by rolandgeider** [comment]
Hi! There is already a PR for adding a dark theme (#246), but it would be useful if there was a switch in the preferences screen to allow the user to use brigth, dark theme or the system preferences. (since the project itself has the hacktoberfest label, your PR would count anyway)

**Comment by AmanNegi** [comment]
Let me know if I can help in any of this @trats08 @rolandgeider.

Happy to help 😊

**Comment by rolandgeider** [comment]
@trats08 do you need any help?

**Comment by AmanNegi** [comment]
@trats08 @rolandgeider any updates? Maybe I could help you with this...

**Comment by rolandgeider** [comment]
@AmanNegi you can checkout the branch in #246 There is still some work to do there, but we could add a switch independently of it

**Comment by rolandgeider** [comment]
This is being worked on in the `feature/material-3 branch`, see also #335, closing here
