### ISSUE TITLE
Improve Login Page interface

### ISSUE THREAD

**Issue by AmanNegi** [wger-project/flutter#264]
## Use case

Currently the Login Page is shabby in terms of design. It is currently usable but having a better visual appeal would be better.

## Proposal

Here's an example of how it might be looking, not exactly but in terms of simplicity of interface. We will use the app color theme and logo and implement it according to our app.

![image-5.png](https://user-images.githubusercontent.com/37607224/195983380-dffb6546-fe19-4d38-9fc3-276df7bee958.png)

**Comment by AmanNegi** [comment]
Can you assign this issue to me? I recently worked with the Login Page and am familiar with the codebase 😊

**Comment by rolandgeider** [comment]
Shabby is indeed the right word 😅 

Sure, go ahead

**Comment by AmanNegi** [comment]
@rolandgeider I have modified the design, let me know if you need some more changes as well.

![IMG_20221020_000303.jpg](https://user-images.githubusercontent.com/37607224/196775398-b628023e-f2b4-4b9d-97d2-e650e3b8ed44.jpg)

> `Old: right  & New: left`

**Comment by rolandgeider** [comment]
yes, much better!

Is the bottom white half like that or is it an artefact of the screenshot?

**Comment by AmanNegi** [comment]
No.. that white part is a part of the design to show the card depth, the same bg color throughout the background seems odd.. I'll create a PR for this 🙂😊

**Comment by AmanNegi** [comment]
@rolandgeider Can you please test and merge this PR.

**Comment by rolandgeider** [comment]
Just tested this and it definitely looks better this way. I was thinking of adding an email icon to the email field so that it is more consistent. What do you think?

**Comment by AmanNegi** [comment]
Yes that might be perfect ✨...

I'll make the required changed and update the PR.

**Comment by AmanNegi** [comment]
@rolandgeider Can you update me on this?

**Comment by AmanNegi** [comment]
@rolandgeider we are currently showing a person icon right?

![image](https://user-images.githubusercontent.com/37607224/197939163-f65f71f8-4e29-482c-b8b9-b76cb444d68d.png)

**Comment by rolandgeider** [comment]
Sorry, I meant while registering

**Comment by rolandgeider** [comment]
![image](https://user-images.githubusercontent.com/2280729/197980611-3e6f3c75-4580-48a2-83f2-84f9d7611f43.png)

**Comment by AmanNegi** [comment]
Oh okay got you. Working on that now 🤗👍

**Comment by AmanNegi** [comment]
@rolandgeider Updated the Registration UI which now looks like this:

![Screenshot_1666934289](https://user-images.githubusercontent.com/37607224/198509075-a7936692-c7aa-4d90-aa54-2b9acd08c7ac.png)

**Comment by AmanNegi** [comment]
@rolandgeider I have updated the Registration UI and it looks like this now:

![Screenshot_1666934959](https://user-images.githubusercontent.com/37607224/198510151-0b60e126-2bad-44f5-a51b-704bb1c85477.png)

**Comment by AmanNegi** [comment]
@rolandgeider is this fine? Or something else is also needed?

**Comment by rolandgeider** [comment]
no, this is fine! Thanks! :)
