### ISSUE TITLE
Change AboutDialog to Full Screen Page

### ISSUE THREAD

**Issue by AmanNegi** [wger-project/flutter#265]
## Use case

Right now, on clicking About Wger we get a dialog which looks like this:

![Screenshot_2022-10-15-16-51-18-42_b440cc4bcc22d07983183a7f8cd04ac8.jpg](https://user-images.githubusercontent.com/37607224/195983857-4e2187d0-4396-43aa-9bef-de9e2f36ea48.jpg)

Dialogs are fine is the information is short and precise. The content we are currently showing is too large to display in a dialog. 

## Proposal

I would suggest to create an About Page and simply show all this content there, for the simplicity of interface. 

![Screenshot_2022-10-15-16-57-48-11_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/37607224/195984065-7d2253f0-f6b9-463c-8ea9-6ce0b50e83cb.jpg)

Something like this would do just fine.

**Comment by AmanNegi** [comment]
Can you assign this issue to me? 😁

**Comment by antarah** [comment]
I would be able to resolve this issue as I have earlier contributed to the issue of Landscape mode as well thus I am well versed with  code.  I m ready to solve this issue please assign me.

**Comment by rolandgeider** [comment]
Can we collect all the licenses from the dependencies? That is one of the reasons we were using the popup, all the necessary legalese is collected automatically

**Comment by AmanNegi** [comment]
I believe we can do that using [this](https://api.flutter.dev/flutter/material/showLicensePage.html)

**Comment by rolandgeider** [comment]
ah cool, yes that looks exactly what we need. I'm assigning this to @AmanNegi since he asked first

**Comment by AmanNegi** [comment]
Thanks @rolandgeider

**Comment by AmanNegi** [comment]
@rolandgeider Just made the appropriate changes for the AboutPage. Here's a screenshot showing the newly created `AboutPage`

![Screenshot_1666762564](https://user-images.githubusercontent.com/37607224/197944210-2f7e5173-3668-425a-9646-afe0e7e9bfb9.png)

**Comment by rolandgeider** [comment]
oh yes, much better!

**Comment by AmanNegi** [comment]
@rolandgeider Added those texts to `app_en.arb`. 🙌
