### ISSUE TITLE
Add Helper Texts in Empty Tabs

### ISSUE THREAD

**Issue by AmanNegi** [wger-project/flutter#281]
## Steps to Reproduce

1. Create a new account in `WGER` and login into the app.
2. After you log in you will be navigated to the home page with 5 tabs.
3. Switching to 2,3 or 5th Tab, shows an empty screen. The tabs are Workout, Nutrition, and Gallery.

**Expected results:** 
It would be great to see a message which says no items available or some helper text at least.

**Actual results:** 
Currently, we see a blank screen with no idea what is happening.

**Comment by AmanNegi** [comment]
@rolandgeider Let me know if this issue is valid and if it is please assign it to me I would be happy to resolve it. 😊🙌

**Comment by rolandgeider** [comment]
yes, informing the user isn't a bad idea. I would use a generic text instead of something specific to the tab as to keep the amount of text that needs to be translated to a minimum (so something like "no items" instead of "no workout routines")

**Comment by AmanNegi** [comment]
Okay a common text would be perfect so that it can be reused. 🤗👍

**Comment by AmanNegi** [comment]
@rolandgeider Any updates on this?

**Comment by AmanNegi** [comment]
@rolandgeider could you please merge this issue by today?

**Comment by rolandgeider** [comment]
I've just approved it so it counts as well 👍🏻

**Comment by AmanNegi** [comment]
Thanks a lot !! 🤗💓✨
