### ISSUE TITLE
Some texts are hard-coded, it is necessary to implement localization

### ISSUE THREAD

**Issue by sandimilohanic** [wger-project/flutter#284]
## Use case

- images notes (file step5images.dart)
- videos button (file video.dart)

... and other similar places.

![Screenshot_70](https://user-images.githubusercontent.com/7765448/198870141-54d2ddd3-e5f1-49a9-9daa-7314c70053ef.png)

**Comment by sandimilohanic** [comment]
Hi @rolandgeider if you approve this,  assign it to me. thx

**Comment by rolandgeider** [comment]
good catch, we definitely want those translated as well. You can use the [same strings used in the web application](https://github.com/wger-project/react/blob/master/public/locales/en/translation.json), then weblate can suggest the same translation (even if their UI sometimes hides these suggestions a bit too much)

**Comment by SamiraHuber** [comment]
Nothing happened here. Is it still open? I would love to do my first open source contribution and if it is still open I think this would be a good first issue for me. @rolandgeider

**Comment by rolandgeider** [comment]
Hi! While it's possible that that specific string has been fixed, there might definitely be others. If you want to give it a try, go ahead

**Comment by FutureYL3** [comment]
Hi, @rolandgeider , is this issue still open? I would like to make my contibution to this project.

**Comment by FutureYL3** [comment]
Hello @rolandgeider , I have submitted a PR to address some hard-coded texts I noticed while reviewing the app. Could you please take a look at it when it is convenient for you?

**Comment by rolandgeider** [comment]
@FutureYL3 thank you for the PR, it's merged. I think there shoudln't be any other hard coded strings left so I'm closing here
