### ISSUE TITLE
Unable to visualize Training Logs

### ISSUE THREAD

**Issue by manto89** [wger-project/flutter#291]
## Steps to Reproduce

1. Create a Workout Plan, put some exercises in said plan
2. Log reps/weight for the plan
3. In 'Workout' section click on the plan
4. Click on the Logs section <img width="48" alt="Screenshot 2022-11-14 at 02 20 19" src="https://user-images.githubusercontent.com/6862296/201556307-b2b8fa0f-3e49-490d-9637-14537989ecbf.png">

**Expected results:** 
The logs of the exercise with a graph showing how reps/weight changed during the last sessions

**Actual results:** 
Empty page (using the release build)
Error 
```
type 'ExerciseBase' is not a subtype of type 'Exercise' of 'key'
```
if using development build

<details>
  <summary>Logs</summary>

```
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building WorkoutLogs(dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#37e3e]], state: _WorkoutLogsState#35182):
type 'ExerciseBase' is not a subtype of type 'Exercise' of 'key'

The relevant error-causing widget was: 
  WorkoutLogs WorkoutLogs:file:///Users/manto89/git/wger-project/flutter/lib/screens/workout_plan_screen.dart:66:16
When the exception was thrown, this was the stack: 
#0      _LinkedHashMapMixin.[]= (dart:collection-patch/compact_hash.dart)
#1      WorkoutPlan.logData (package:wger/models/workouts/workout_plan.dart:103:33)
#2      _WorkoutLogCalendarState.loadEvents (package:wger/widgets/workouts/workout_logs.dart:135:44)
#3      _WorkoutLogCalendarState.initState (package:wger/widgets/workouts/workout_logs.dart:125:5)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5015:57)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
...     Normal element mounting (4 frames)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#10     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#11     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3586:20)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
```

</details>

## Solution
I'm already working on a solution on my local fork. I assumed (correct me if I'm wrong) that Exercise has localization while exerciseBase doesn't so my efforts are focused on that.
I found that ExerciseBase has a method getExercise that needs localization. In particular the code used everywhere else is
```
Localizations.localeOf(context).languageCode
```
### What I did
1. `libs/models/workouts/workout_plan.dart:98`  changed Exercise to ExerciseBase
2. `libs/widgets/workouts/workout_logs.dart:137` it's the first place getLogs is used so I tried to use `Localization.localeOf(context).languageCode` but since I'm still inside LoadEvents() it cannot be used, I've used a workaround like `exerciseBase.getExercise("en-EN")`
3. `libs/widgets/workouts/log:49` This component was failing because the server has a bug (see issue linked below) so i enabled the loading spinner even if the api fails 
### What still need to be done ( I NEED HELP)
1. Find where to put the localization to transform from ExerciseBase to Exercise in `libs/widgets/workouts/workout_logs.dart:137`

**Comment by rolandgeider** [comment]
See discussion in corresponding issue for the backend
