### ISSUE TITLE
Instead of showing exercise names the app shows exercise id

### ISSUE THREAD

**Issue by mohammadrafigh** [wger-project/flutter#297]
## Steps to Reproduce

![signal-2022-11-22-20-43-46-125](https://user-images.githubusercontent.com/6737508/204082450-673a26aa-32c1-4525-bff8-80e4bf375bc6.jpg)

1. Start training mode
2. Press menu button on top right of the screen
3. You see ids instead of names

**Expected results:**

Get exercise names.

**Actual results:**

We get ids.

**Comment by Harshit933** [comment]
hey! can you please assign me to this issue

**Comment by rolandgeider** [comment]
Sure, go ahead. You can also take a look at the PR #300 which has already some work put into it

**Comment by Harshit933** [comment]
On it!

**Comment by aman123424** [comment]
hey! Can you please assign this issue to me, if not solved yet then

**Comment by rolandgeider** [comment]
Hi @aman123424 ! I think @Harshit933 is still working on this

**Comment by aman123424** [comment]
Okay, @Harshit933 , can we collaborate if you need help to resolve this?

**Comment by Harshit933** [comment]
Hey you can work on this issue, I am unassigning myself.

**Comment by aman123424** [comment]
Okay sure

**Comment by jagrutatwork** [comment]
Is this issue resolved?
