### ISSUE TITLE
Gallery Screen

### ISSUE THREAD

**Issue by jfrys** [wger-project/flutter#306]
## Use case

The Gallery Screen is in need of a prompt for users.

<img width="337" alt="gallery" src="https://user-images.githubusercontent.com/93684643/204167669-dbccf3c8-8436-44db-88ef-a6362564f2a7.png">

## Proposal

Since the Gallery is included on the main tab bar - the initial screen should have some sort of prompt for users to know what kind of media they should be uploading to this screen. I am not too sure personally what pictures would be best here, whether it's progress photos of myself, the food I eat or anything else that could relate to this app. I believe a simple text prompt of what wger is looking for users to upload on this screen would go a long way.

**Comment by tavkeer** [comment]
can i contribute to this issue

**Comment by tavkeer** [comment]
> ## Use case
> The Gallery Screen is in need of a prompt for users.
> 
> <img alt="gallery" width="337" src="https://user-images.githubusercontent.com/93684643/204167669-dbccf3c8-8436-44db-88ef-a6362564f2a7.png">
> 
> ## Proposal
> Since the Gallery is included on the main tab bar - the initial screen should have some sort of prompt for users to know what kind of media they should be uploading to this screen. I am not too sure personally what pictures would be best here, whether it's progress photos of myself, the food I eat or anything else that could relate to this app. I believe a simple text prompt of what wger is looking for users to upload on this screen would go a long way.

does this issue still needs work

**Comment by tavkeer** [comment]
can i

**Comment by tavkeer** [comment]
> ## Use case
> The Gallery Screen is in need of a prompt for users.
> 
> <img alt="gallery" width="337" src="https://user-images.githubusercontent.com/93684643/204167669-dbccf3c8-8436-44db-88ef-a6362564f2a7.png">
> 
> ## Proposal
> Since the Gallery is included on the main tab bar - the initial screen should have some sort of prompt for users to know what kind of media they should be uploading to this screen. I am not too sure personally what pictures would be best here, whether it's progress photos of myself, the food I eat or anything else that could relate to this app. I believe a simple text prompt of what wger is looking for users to upload on this screen would go a long way.

can i work on this
