### ISSUE TITLE
Allow custom root ca's for ssl verification

### ISSUE THREAD

**Issue by ryan77627** [wger-project/flutter#330]
## Use case

I self host wger and do not expose it to the public internet. For various reasons, I choose to protect my internal services using HTTPS as well, using a custom root ca. I have this CA trusted on my android device, however wger does not recognize it.

## Proposal

Allow wger (at least the android build) to utilize the user ca store within android. I am not too familiar with android app development, but it seems that it is just a value that needs to be inserted into the AndroidManifest.xml file.

For an example of this being implemented, see: [this commit in the home assistant app.](https://github.com/home-assistant/android/pull/194/commits/2b3b0b73e614f716fba7f1d251dcdc03569a8820)

**Comment by rolandgeider** [comment]
Yes, we actually implemented this, but forgot to set the android:networkSecurityConfig value 🤦🏻  This will be available on the next release

See #116
