### ISSUE TITLE
Move theme to material 3 and add dark theme

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#335]
See e.g. https://docs.flutter.dev/development/ui/material3-updates

**Comment by Mittal-Sudhanshu** [comment]
please assign this to me

**Comment by rolandgeider** [comment]
Hi @Mittal-Sudhanshu go ahead!

Do you need access to the test server?

**Comment by Mittal-Sudhanshu** [comment]
PR submitted do check it out

**Comment by rolandgeider** [comment]
Dark theme will be available when this is merged

Current work in progress:
![Screenshot_20231109_192334](https://github.com/wger-project/flutter/assets/2280729/6b07aa4d-2869-4881-986a-0411c7981760)
