### ISSUE TITLE
Add other measurements beside body weight

### ISSUE THREAD

**Issue by peschie1967** [wger-project/flutter#34]
I would like to check and log my body data, such as fat percentage, muscle mass, etc. on a regular basis. The values should also be displayed graphically so that the changes are visible.

**Comment by rolandgeider** [comment]
Hi! Yes, we already have plans for this, but I can't give a timeline for it

**Comment by rolandgeider** [comment]
https://github.com/wger-project/wger/issues/133

**Comment by rolandgeider** [comment]
Closing this duplicate issue, but this is being worked on
