### ISSUE TITLE
Duplicating exercises on save Android, not able to delete

### ISSUE THREAD

**Issue by JoeDet** [wger-project/flutter#341]
## Steps to Reproduce

1. Add exercise with Android app
2. Save exercise
3. No feedback if exercise is saved, so tried to save again
4. Ended up duplicating the exercise 4 times

**Expected results:**
New exercise

**Actual results:** 
Got 4 new ones, not able to remove the duplicates. And when editing, not able to delete photos and turn the duplicate into a different exercise.

<details>
  <summary>Logs</summary>

```
```

</details>

**Comment by rolandgeider** [comment]
yes, you are right, the submission form could use a bit of polishing. I have deleted the duplicated exercises
