### ISSUE TITLE
Start time of workout session should be before the end

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#35]
Add validator to enforce that the end and start times of a session (last page of gym mode) are in the correct order

**Comment by rolandgeider** [comment]
I think TimeOfDay objects can't be directly compared, you will probably have to do a bit of data massaging

**Comment by arun-muralidharan** [comment]
Yes, I'll have to create a DateTime object from TimeOfDay and then compare them using isAfter/isBefore. Something came up last night and I couldn't get to it. I'll do it this evening.
