### ISSUE TITLE
Adding exercise with custom image to workout does not work.

### ISSUE THREAD

**Issue by RemcoSchrijver** [wger-project/flutter#359]
## Steps to Reproduce

Try to add an exercise with a custom image to a set, you can find the exercise but you cannot select it to add it to the set. This does work with exercises where I didn't add a custom image.

![IMG_20230308_153447](https://user-images.githubusercontent.com/45097990/223742497-60683ffc-4416-4882-ae26-8013e630b7c1.jpg)

**Expected results:** 
I expected to be able to click the exercise with the image and then add it.

**Actual results:** 
No behaviour at all.

**Comment by rolandgeider** [comment]
yeah, that definitely shouldn't happen, i'll take a look

**Comment by RemcoSchrijver** [comment]
Hmm whilst debugging this in android studio this works just fine, so I am unsure why this issue came up on my normal phone.

**Comment by rolandgeider** [comment]
Are you using the version from the play store or fdroid? The one from fdroid is older because we can't update it

**Comment by RemcoSchrijver** [comment]
I am on the playstore version, and the latest one 1.5.2, but right now when I try to search for an exercise I get an error when searching, which stems from [this issue](https://github.com/wger-project/wger/issues/1269)

**Comment by rolandgeider** [comment]
This is a backend problem, https://github.com/wger-project/wger/issues/1319

Closing here
