### ISSUE TITLE
Feature Request related to improving User Profile Page UI

### ISSUE THREAD

**Issue by tejasbirsingh** [wger-project/flutter#381]
## Use case
- Currently, the User Profile page does't look that much good due to the UI. The text/fields should be shown on the top instead of bottom to make it look a bit better.
- We can also make the List Tile view widgets more attractive by simply adding some icons in the front and few more things.

## Proposal
- Top align the fields in User Profile Page.
- Improve the UI by adding leading icons. Will try to add screenshots in the comments.
- Maybe we can add border if it looks good.
- Any other idea or suggestions are welcome and would be appreciated.

Below if the screenshot after simply moving it to the top - 

<img src="https://user-images.githubusercontent.com/48317772/234942649-571cb86b-6686-47ec-8b6a-ae6a9701e6bf.png" width="200" height="400" />

I would like to work on this if possible **please assign this request to me**.
Thanks

**Comment by tejasbirsingh** [comment]
Did some very basic change that will match the look of the apps theme. Didn't change too many things as it will not blend with the overall app. 

<img src="https://user-images.githubusercontent.com/48317772/235288912-60887aaf-12b3-4552-99bd-91aac4e1b7cd.png" width="200" height="400" />

Any suggestion on what more should be done ?

**Comment by tejasbirsingh** [comment]
Did some very basic change that will match the look of the apps theme. Didn't change too many things as it will not blend with the overall app. 
**How I aligned the form fields on the top ?**
- Currently, we use FormScreen which is used by multiple pages so changing the alignment on it will result in changes for all pages using this.
- I added a new argument for the class - isTopAligned which is not a required value as its default value is false.
- I passed it from the forms class under User as true to make the fields top aligned.

<img src="https://user-images.githubusercontent.com/48317772/235289101-06583d27-eb3b-4627-b41b-da87fe82e076.png" width="200" height="400" />

Any suggestion on what more should be done ?

**Comment by rolandgeider** [comment]
Hi! I would leave everything at the bottom, then it's easier to access everything with the thumb

But you are right that the icons are an improvement and I would accept a PR if you want to send one. I'm also now thinking that since both the email address and whether its verified or not are related, they could be grouped somehow

**Comment by tejasbirsingh** [comment]
Hey,

Sure, we can keep it at bottom if its intentional to make it accessible.
I was also thinking that those 2 fields are for kind of for the same thing. 

So, I have made some changes to merge them into one field along with adding icons and keeping the fields at bottom.
Now our text field has a icon button at the end which will send the verification email in case not verified. Screenshots attached below.

**Case when email is not verified -** 

<img src="https://user-images.githubusercontent.com/48317772/235302687-68d16ead-c667-4676-8cdb-e1b512fe3e56.png" width="200" height="400" />

**Case when email is verified -** 

<img src="https://user-images.githubusercontent.com/48317772/235302717-c391c44e-628b-4b98-9dec-5512cddb9dc9.png" width="200" height="400" />

Do you have any suggestion on icons or color of icons ?

Thanks !

**Comment by tejasbirsingh** [comment]
Hey,

Sure, we can keep it at bottom if its intentional to make it accessible.
I was also thinking that those 2 fields are for kind of for the same thing. 

So, I have made some changes to merge them into one field along with adding icons and keeping the fields at bottom.
Now our text field has a icon button at the end which will send the verification email in case not verified. Screenshots attached below.

**Case when email is not verified -** 

<img src="https://user-images.githubusercontent.com/48317772/235302881-1ae2840b-f547-4cad-91e8-49f7ed0436a4.png" width="200" height="400" />

**Case when email is verified -** 

<img src="https://user-images.githubusercontent.com/48317772/235302717-c391c44e-628b-4b98-9dec-5512cddb9dc9.png" width="200" height="400" />

Do you have any suggestion on icons or color of icons ?

Thanks !

**Comment by rolandgeider** [comment]
yeah, those two fields can definitely be combined. The question is how to make it clear that the icon on the right can be clicked to send the confirmation email? Perhaps we could add some kind of button below the field for unverified users and once the account was verified we hide it and show the green check mark like in the screenshot?

**Comment by rolandgeider** [comment]
I'd like the centered button more, but perhaps we could use an outlined one, then it doesn't seem like that one and "save" are equally important

**Comment by tejasbirsingh** [comment]
Agreed ! How does this look then - 

**<img src="https://github.com/wger-project/flutter/assets/48317772/4fc4061d-9159-48dd-bfb4-625092a8469b" width="200" height="400" />**

**Comment by rolandgeider** [comment]
yes, much better!
