### ISSUE TITLE
Validating username has a little problem

### ISSUE THREAD

**Issue by xiaoyaozuizui** [wger-project/flutter#385]
https://github.com/wger-project/flutter/blob/25e9622a801c047267f0117090b2b4f5eafb8e32/lib/screens/auth_screen.dart#L248-L254
That will never validate 'value.isEmpty'

**Comment by Jiggy9** [comment]
Hello,

Thank you for your comment regarding the validation issue in the `auth_screen.dart `file. I have updated my pull request to address this issue. Could you please take a look at the changes and let me know if they meet your requirements?

**Comment by rolandgeider** [comment]
This was fixed with #388
