### ISSUE TITLE
[Bug] Null Check Operator used on a null value error while registering but user getting registered successfully

### ISSUE THREAD

**Issue by tejasbirsingh** [wger-project/flutter#389]
## Steps to Reproduce

1. Download the wger app from playstore
2. Go to register and fill your details
3.  Press register 
4. A dialog box will be shown saying - 'Null check operator used on a null value"
5. Close the dialog as the user is successfully registered and try logging in.

**Expected results:** 
- After the user registers successfully the app should not throw any error message

**Actual results:** 
- Currently, I am getting error dialog after successfully registering the user.

Screenshot - 

<img src="https://github.com/wger-project/flutter/assets/48317772/afeaa869-733f-4e41-9814-0369d3a5d557" width="200" height="400" />
 

I will try to find more details around the bug. I will need to setup the back-end to test the app on emulator right ?

**Comment by Yeasin00p** [comment]
i wan't to work on this issue

**Comment by droidbg** [comment]
@rolandgeider @tejasbirsingh is this issue still valid?
 if it is can you assign it to me. 
 if not can you close this issue.

**Comment by rolandgeider** [comment]
sorry for the late reply, this issue has already been fixed
