### ISSUE TITLE
The App is all in Deutch - Missing language set

### ISSUE THREAD

**Issue by edgui** [wger-project/flutter#40]
## Steps to Reproduce

1. ... All app is in Deutch. Doesn't have a option to change language.
2. ...
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

</details>

**Comment by rolandgeider** [comment]
Hi! The app uses the system's languages or if no translation is available, English as a fallback. Can you check in your language settings that you don't have German?

**Comment by edgui** [comment]
Thank  You for a quick reply!
It's now solved. Yes, the issue was in the language settings, mine was Portuguese. So I added English, and set it as default. It worked. Then I returned to Portuguese as default, and the app is still in English (which for me is not bad at all). 
By the way, congratulation on the amazing app!!

**Comment by rolandgeider** [comment]
Glad that it works now. Closing the issue
