### ISSUE TITLE
Allow editing the exercise/set order

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#41]
## Use case

it's currently not possible to change the order of sets once added to a workout.

## Proposal

There is already an order field for the sets that's populated during creation, so there is nothing that needs to be added on the backend. I'm not sure if we need a package for this or flutter has the necessary tools

**Comment by arun-muralidharan** [comment]
There is Flutter's native `ReorderableListView` widget. We could use that; of if that doesn't work for us, there is also the [flutter_reorderable_list](https://pub.dev/packages/flutter_reorderable_list) package.

I'll start working on this.

**Comment by rolandgeider** [comment]
Awesome! I'm not sure if the sets are currently rendered with ListTiles or something else, in case the  RecordableListView needs some specific child widgets to work

**Comment by arun-muralidharan** [comment]
It is possible that `ReorderableListView` implements `ListView`. I'll take a look.

**Comment by M123-dev** [comment]
@rolandgeider, is there even the possibility to do this on the webside?

**Comment by rolandgeider** [comment]
There will be! It's on my to-do
