### ISSUE TITLE
Prompt users to submit an exercise when no exercises can be found

### ISSUE THREAD

**Issue by TheITFirefly** [wger-project/flutter#418]
## Use case
The workflow for new users does not make it apparent that they can contribute exercises. Current workflow (or at least what I followed as a new user) looks like:
1. Add workout plan from dashboard
2. fill out days from workout plan
3. add exercises to each day
During this workflow users never touch the workout tab, where they have to touch the 3 dots to know that they can contribute exercises. This can lead to frustration, as new users won't find how to contribute their exercises unless they actively go looking for it.

## Proposal
When adding exercises to a workout plan, there is currently an entry which states "No Items Found!" when there are no workout names that match their search. An interactive button taking users to the contribution page in place of/in addition to the current message is what I'm proposing to fix this. I'd love to just create a fix myself, but have never worked with flutter before (I am willing to learn though).

**Comment by KritarthChavda** [comment]
Hey, I would like to Contribute. I have been developing apps in Flutter for a year, so i think i would be able to help.

**Comment by rolandgeider** [comment]
hi @KritarthChavda! sure, go ahead! The readme should have all the infos to get you started, but if there's any problem or you run into problems, just ping me

**Comment by Milksheyke** [comment]
Since KritarthChavda hasn't made the contribution yet, I hope they don't mind if I take this as my first contribution.
[Pull request created](https://github.com/wger-project/flutter/pull/479). Very open to criticism. Let me know if any changes are necessary.
