### ISSUE TITLE
Can't open published flatpak

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#424]
```
flatpak run de.wger.flutter
Gtk-Message: 15:34:51.356: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:34:51.358: Failed to load module "canberra-gtk-module"
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'setLogEnabled': /app/wger/lib/libflutter_linux_gtk.so: undefined symbol: setLogEnabled
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33)
#1      GeneratedBindings._setLogEnabledPtr (package:flutter_zxing/generated_bindings.dart:42)
#2      GeneratedBindings._setLogEnabled (package:flutter_zxing/generated_bindings.dart)
#3      GeneratedBindings.setLogEnabled (package:flutter_zxing/generated_bindings.dart)
#4      setZxingLogEnabled (package:flutter_zxing/src/logic/zxing.dart:30)
#5      ZxingMobile.setLogEnabled (package:flutter_zxing/zxing_mobile.dart:23)
#6      main (package:wger/main.dart:57)
#7      _runMain.<anonymous closure> (dart:ui/hooks.dart:131)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```

**Comment by bbkz** [comment]
The barcode reader Flutter zxing states that it's not working on linux.

* https://pub.dev/packages/flutter_zxing

>Linux (not working yet)

At least disabling `zx.setLogEnabled(kDebugMode);` in the `main.dart` got it working for me... maybe there needs to be done some distiction between a linux build and others?

**Comment by rolandgeider** [comment]
It will probably crash when clicking on the scan button anyway, but at least the app will start. I could have sworn that the last flatpak version also had the scanner but worked

**Comment by bbkz** [comment]
Yes, definitly not a solution ;-) but for me having a laptop available where i train, it fits my case.

**Comment by rolandgeider** [comment]
Have removed the line, will publish a new version as soon as I find some time for that

**Comment by bbkz** [comment]
Oh. thank's. I have built it for me already with the workaround, so there is no rush or need for a workaround from my side :-0

**Comment by rolandgeider** [comment]
published flatpak works again
