### ISSUE TITLE
Chart polishing

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#433]
List of things to do (on the `fix/replace-chart-lib` branch)

All
- [x] Check if spacing of values in y axis breaks depending on value ranges. Ideally we'd have two labels besides the start and end ones
- [x] Better spacing of x axis. It seems that fl charts always shows entries at the beginning and the end of the axis. Since this is not some important financial chart and should just show a tendency, I'd say that one or two more labels are enough
- [ ] Better Date format, MMMd or yMd if there are entries from last year

Workout log (`LogChartWidgetFl`)

- [x] Better margins
- [x] Fix chart colors (fix helper function so that we always get the same color from the same rep range). Note that we need to draw a line for every repetition range the user has done (so e.g. all entries for 8 reps, all for 10, all for 12, etc.) Realistically there probably isn't going to be too many, but we need to make sure everything still works fine
- [x] Add legend below the axis. Each color corresponds to a repetition range (e.g. blue for 8 reps, orange for 10 reps)
- [x] Fix tooltip. Ideally we would do something like "🟦 8 reps: 51kg"
- [ ] The labels for the y axis looks ugly and too far away from the axis but we need to consider that we can have five digits in total plus the weight unit (which is currently only "kg"). If there is an easy way to dinamically change this, we could try it+

![Screenshot_20231010_173428](https://github.com/wger-project/flutter/assets/2280729/529a015d-f063-4ed9-896f-ff0ef13c3ed3)

Nutrition diary chart (`NutritionalDiaryChartWidgetFl`)

- [x] Add a legend (alternatively, we could incorporate it to the heading)

![Screenshot_20231010_174336](https://github.com/wger-project/flutter/assets/2280729/836c7490-ecdc-4872-ba37-255ecff2a44e)

Measurement chart (`MeasurementChartWidgetFl`)

- [x] Move from core/charts.dart to measurement
- [x] Add the unit to the tooltip (so e.g. "80 kg" or "12 %")

![Screenshot_20231010_174506](https://github.com/wger-project/flutter/assets/2280729/19954485-d1eb-4d41-96b0-69e19240827e)

**Comment by Abhisheksainii** [comment]
Hello, I am working on the Measurement chart
The tooltip part is done.
Had query if the core/charts.dart needs to be moved to measurements folder?
