### ISSUE TITLE
Feature request: Add dark mode

### ISSUE THREAD

**Issue by 0scvr** [wger-project/flutter#438]
## Use case

It just looks better x) and easier on the eyes in the evenings.

## Proposal

It would be nice to implement dark mode in the app as well as a switch in the settings to toggle between light and dark mode. By default wger should match the system theme.

**Comment by shubham3246** [comment]
Can I be assigned on this?

**Comment by rolandgeider** [comment]
This is being worked on in the `feature/material-3` branch, see also #335, closing here
