### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#448]
Currently, `nutritional_meal_form_test.dart` can be a bit flaky, since we compare the current time so sometimes this fails because the widget was rendered in the next/previous minute. It would be better if we would just mock the current time to whatever value we need

see also
https://pub.dev/packages/clock
https://medium.com/steeple-product/mocking-time-in-flutter-tests-724c42a28daf

**Comment by watcher6280** [comment]
@rolandgeider Can I work on this one?

**Comment by rolandgeider** [comment]
sure, go ahead!

I'm not sure if we really need that package though, might be enough to rewrite a bit the test

**Comment by watcher6280** [comment]
Thanks, I'll add my PR and we can see if it is worth it.
