### ISSUE TITLE
Barcode scanner

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#5]
When https://github.com/wger-project/wger/issues/422 is done, it would be possible to implement a barcode scanner, instead of searching for products by name

**Comment by rolandgeider** [comment]
There are widgets for this, e.g. https://pub.dev/packages/flutter_barcode_scanner/score

**Comment by sandimilohanic** [comment]
Hi @rolandgeider , I am a beginner in flutter, but I would like to try to solve this problem. Can I work on this issue?
Thanks.

**Comment by rolandgeider** [comment]
Hi! Somebody else had asked to to do this issue, I've written them again to confirm

**Comment by AdoHal** [comment]
Hi! Thats me, you can assign it to me.

**Comment by AdoHal** [comment]
Hi! Its me. You can assign it to me. Thanks.
