### ISSUE TITLE
Double displayed training plans

### ISSUE THREAD

**Issue by M123-dev** [wger-project/flutter#53]
When the app is loading (on startup) and you visit the Training section on the bottom navigation bar and you go back and revisit again it all workouts are displayed double(three times, four times, ....).

**Comment by rolandgeider** [comment]
Mhh, interesting. We should probably refactor that loading screen and only show the navigation once everything is downloaded. Perhaps even inform the user what exactly is being currently fetched.

**Comment by M123-dev** [comment]
@rolandgeider I was just looking into this, but one question is it better to move the futureBuilder from dasboard.dart to main.dart or to home_tabs_screen.dart
