### ISSUE TITLE
Download .apk from github directly with Obtainium

### ISSUE THREAD

**Issue by HomemadeAdvanced** [wger-project/flutter#530]
I would like to pull the latest .apk directly from github using Obtainium. In order to do this, the latest released .apk would have to be listed under Releases. Would this be possible or is there another way to get the latest .apk directly from github?

**Comment by rolandgeider** [comment]
hi! we currently build the an abb file, upload it to the play store and then delete it, uploading it to the release shouldn't be a problem (or do you need an apf file?)

**Comment by HomemadeAdvanced** [comment]
An apk file would be great because I think an abb file does not work with Obtainium.
