### ISSUE TITLE
Bad internet duplicate exercise entries

### ISSUE THREAD

**Issue by M123-dev** [wger-project/flutter#54]
If you have a bad internet connection and you want to save an exercise entrie, you can press the button again until you get a response from the server. Either you have to click away several error alert dialogs or if the requests are accepted there are multiple entry,

The button should be disabled until there is a response (or a timeout).

**Comment by rolandgeider** [comment]
I have also noticed this while saving logs in the gym mode, but this is something that will probably happen with all forms that save something to the server (which are basically all of them).

**Comment by Dolaned** [comment]
Idemponent requests could help this

**Comment by rolandgeider** [comment]
You are right, at the moment we use POST requests to create objects, perhaps using PUT would help. On the other hand we don't have any ids at the time to identify the resource.

Disabling the button or showing some kind of spinner till "something happens" is probably the best solution usability wise anyway

**Comment by ThilinaTCH** [comment]
@rolandgeider can I work this?

**Comment by rolandgeider** [comment]
sure
