### ISSUE TITLE
Better add sets screen

### ISSUE THREAD

**Issue by M123-dev** [wger-project/flutter#56]
When adding a new set to a workout day it is currently not clear that you have to press save for each exercise or you will add a superset.

I have seen the button in the TextField and I know it is the same system as on the website but it is confusing at first.

**Comment by rolandgeider** [comment]
There is an explanation text in the help button, but yeah, how many users read that

Perhaps adding a "plus superset with" between the exercise blocks would make this more obvious?

**Comment by M123-dev** [comment]
Maybe we can remove the search bar after the exercise is choosen and add it back in with a "Add superset" button

**Comment by rolandgeider** [comment]
Yes or something like that. Changing the placeholder text is also perhaps enough and is simpler to do
