### ISSUE TITLE
[BUG] Missing double workout entries

### ISSUE THREAD

**Issue by M123-dev** [wger-project/flutter#58]
## Steps to Reproduce

When in a workout exercise with multiple sets and you save the sets with the same value it only gets displayed once. (See video)

<details>
  <summary>Screen recoding</summary>

https://user-images.githubusercontent.com/39344769/124731409-7cbb7f00-df12-11eb-898a-ace87ed989a0.mp4

</details>

**Expected results:** 

The second set with the same amount of weight and reps should also be displayed.

**Actual results:** 

It does not get displayed but saved Server-side (Can bee seen in the logs on the webside)

**Comment by rolandgeider** [comment]
I just though about this last week!

In the list only distinct values are displayed, so if you did all the sets with the same weight/reps, only one will be shown. The rest are saved to the DB and displayed e.g. in the log view in the workout page, but I didnt want to "pollute" this list with unnecessary data. The idea was that you will realistically only do a couple of combinations so you should be able to find the one you need quickly.

But you are right that this logic is not transparend to the user and looks like a bug. BTW I should also check that if there are the same entries for different dates, the latest one should be shown

**Comment by M123-dev** [comment]
Ohh you can click on them, I did not know that. The icon is for me rather means that I save the values to my clipboard. 

I think to avoid confusion we should either make it a complete history or make it a quick selection where the date is either not shown at all or maybe something like "Last time done:".

**Comment by rolandgeider** [comment]
yeah, you "copy" them over 😁 Perhaps (subtly) flashing the form elements would help. I also like the "last time done" idea, showing how old the entries are is important

**Comment by ThilinaTCH** [comment]
Can I work on this?

**Comment by rolandgeider** [comment]
you got it
