### ISSUE TITLE
[BUG] Phone crash

### ISSUE THREAD

**Issue by M123-dev** [wger-project/flutter#59]
Must be further investigated

In Gym mode when entering values, the app crashes relatively often (sometimes up to 3x per hour).

These crashes look like that the app freezes and after about 20 seconds my phone completely shuts down. As far as I can tell so far, it happens when I do things very quickly. 

I assume it will be a null error, probably when accessing something the server hasn't respondet to yet. I hope it will be solved by #18 . But until then including sentry is probably a good idea. 

https://sentry.io/pricing/
https://pub.dev/packages/sentry

**Comment by rolandgeider** [comment]
it completely crashes??? What I have seen when the connection is not great (hello McFit in the basement) is that the phone will wait till the response comes or throws a timeout, but never that the application nor the phone was unresponsive

**Comment by M123-dev** [comment]
Yeah the whole phone, this is annoying during a workout, especially now during corona where there is a fixed time period in my gym.
I can give a few more infos:

| Phone       | Samsung Galaxy S21                                 |
| ----------- | -------------------------------------------------- |
| Connections | Wifi (Public Gym Hotspot) + Bluetooth (Smartwatch) |
| Language    | DE                                                 |
| OS          | Android 11, One UI 3.1                             |

**Comment by M123-dev** [comment]
I did some further investigations, this could be a problem with `flutter_html`, 
Some have suggested that adding wake lock permission fixed their problem, see [here](https://github.com/flutter/flutter/issues/60576#issuecomment-781779417)

**Comment by rolandgeider** [comment]
Cool! Thanks I'll take a look

**Comment by dgurudot** [comment]
We even tried the WAKE_LOCK but that didn't help on Samsung devices. 

We have to press multiple times for any touch to be recognized on device although we could clearly see logs on console when we do press.

We added the following on all three AndroidManifest.xml files (debug, main, profile)

<uses-permission android:name="android.permission.WAKE_LOCK"/>

We also tried using the wakelock package and added the

await Wakelock.enable();

and it didn't help to resolve this issue.

**Comment by rolandgeider** [comment]
Thanks for testing this! If the flutter_html package is somehow the source for this, we could try removing the exercise description and see if it changes something.

**Comment by dgurudot** [comment]
I don’t have flutter_html package in pubspec but it is quite possible that some other package might be using it under the hood

**Comment by rolandgeider** [comment]
@M123-dev I have released a new version of the app (should show up as an update in the next hours). It has the WAKE_LOCK permission as well as current dependencies and finally sound null safety. Let's hope this fixes the issue!

Independently of this, I should take some time and see how hard it would be to integrate sentry.

**Comment by M123-dev** [comment]
Thanks @rolandgeider I tested the new version and wasn't able to reproduce the error anymore. 🎉

**Comment by rolandgeider** [comment]
Awesome! I would still prefer to know what was causing it but... 🤷🏻‍♂️

**Comment by M123-dev** [comment]
@rolandgeider at least it is fixed. If it or something similar occurs again, I'll let you know.

**Comment by dgurudot** [comment]
> @M123-dev I have released a new version of the app (should show up as an update in the next hours). It has the WAKE_LOCK permission as well as current dependencies and finally sound null safety. Let's hope this fixes the issue!
> 
> Independently of this, I should take some time and see how hard it would be to integrate sentry.

My app is not null safe since several dependencies are not null safe yet and also migration tool didn't help much and still had tons of errors. I am not sure if the issue is due to null safety.

I added the WAKE_LOCK permission in AndroidManifest.xml as given below

<uses-permission android:name="android.permission.WAKE_LOCK"/>

What dependencies are you referring above ?

I still have this issue on all Samsung phones and affecting customers. Kindly help.

**Comment by rolandgeider** [comment]
In our case, [this is how the depencencies changes](https://github.com/wger-project/flutter/compare/release/1.2.0..release/1.2.1#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25). You can move your app to null safety, even if not all dependencies support it, I also spent quite some time till everything worked.

**Comment by M123-dev** [comment]
@dgurudot 

First of all have you added the wake lock permission to **ALL** profiles, like @rolandgeider did here:
https://github.com/wger-project/flutter/commit/df8beaa379e9a921976d1eb40ab4b14c0d3e3f9d

When you've done that try to bring all dependencies up to date and while doing that you can check which dependencies use flutter_html. 

When you visit a package on pub.dev you can see on the right side which packages this package uses.
Of course don't forget to run `flutter pub get .` after that.

When any of the packages you use uses flutter_html you should check if it uses the latest version.
The easiest way would be to add the latest flutter_html version to your own pubspec.yaml.

When you now run `flutter pub get .` again and it throws an incompatability error at least one of the packages uses another version. (More infos on that in the error message) You should be able to fix this with dependencie overrides in your pubspec and if this does not work you can still download the problematic (most likely not anymore maintained) package, use the local version and update the flutter_html package there.



--------------

When it all does not fix the problem its probably not related to flutter_html now you have to debug what exactly causes the problem.

1. Check if the analyzer throws any errors `flutter analyze . ` and of course fix them.
 
2. When you have a Samsung device:
Install your app on the phone, connect your phone via ADB Logcat to your computer and check the logs.

3. When you don't have a Samsung device:
Get yourself a free Sentry account, include it in your app, ship the new version and check the online console. https://docs.sentry.io/platforms/flutter/
