### ISSUE TITLE
Cannot register. 

### ISSUE THREAD

**Issue by randombullet321** [wger-project/flutter#595]
## Steps to Reproduce

1. Tried logging in. Gives an error "An Error Occurred! Detail Invalid token header. No credentials provided." 
2. username and password are generated via a password manager.
3. Test password is "UD6Mp#*y05K&nI@Mi^51" (Perhaps too long or invalid characters)?

**Expected results:** Account creation

**Actual results:** An Error Occurred! Detail Invalid token header. No credentials provided." 

<details>
  <summary>Logs</summary>

```
```

</details>

**Comment by I-I-IT** [comment]
Can confirm @dieter_de please look into this!

**Comment by Bourjois** [comment]
Bump. I also just ran into this problem

**Comment by I-I-IT** [comment]
Fixed for me, maybe [this PR](https://github.com/wger-project/wger/commit/cc8a5528c28d80e4db7386a08b3ba9dab6f41fa2)  is the cause.

**Comment by szfkamil** [comment]
Experiencing the same problem, tried different e-mails and passwords, but keep getting the same output.

**Comment by I-I-IT** [comment]
Are you on the latest version ? Did you try to register on the website

**Comment by rolandgeider** [comment]
hi! after not really being able to reproduce this, we've removed some logic on the backend that were definitely behind this, so this issue can finally be closed
