### ISSUE TITLE
Android App doesn't detect fitness exercises 

### ISSUE THREAD

**Issue by I-I-IT** [wger-project/flutter#617]
## Steps to Reproduce

1. ...<Open Android App
2. ...Launch workout
4. ... Type exercise name
5. Do the same on mobile website

https://github.com/wger-project/flutter/assets/78900789/de5c93c2-05ed-4a42-afc3-57f3756616e2

**Expected results:** 

When I type an exercise, a dropdown list appears and I can input my sets
**Actual results:** 
Nothing, just appears in notes. Please see Screen Recording
<details>
  <summary>Logs</summary>

```
```

</details>

**Comment by rolandgeider** [comment]
hi! you need to add the exercises to the sets, then you can start the gym mode with those exercises. The notes field is just to add some thoughts etc about the training session.
<video src="https://github.com/wger-project/flutter/assets/2280729/2f1c9bec-c955-490b-af0d-925755df0347">

That being said, this will change in the future so there is a dedicated (and obvious) edit mode
