### ISSUE TITLE
Set weight interface seems clumsy

### ISSUE THREAD

**Issue by ysalmon** [wger-project/flutter#628]
## Steps to Reproduce

1. open wger app for android
2. in the Weight section, click +

In addition :
3. click the ``-`` or ``+`` around the displayed weight.

**Expected results:** 
1.2. The selected date for adding a weight measurement should be today.

3. Increment or decrement in weight should be practical, ie. either 0.1 kg or 0.05 kg.

**Actual results:** 
1.2. The selected date is the day before (maybe because that was the day for which a measurement was last stored).

3. The weight increment/decrement is 0.25 kg, which is impractical when your scale gives measurements in steps of 0.1 kg.

**Comment by rao-suraj** [comment]
I can work on this if you want it to get changed.

**Comment by Dieterbe** [comment]
this was bothering me too. the fix has been merged, and should appear in the playstore/appstore soon
