### ISSUE TITLE
Don't use shared preferences to store data

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#64]
Shared preferences should only be used to store… preferences and not dump data in it (like we do with the exercise cache)

See also #161

**Comment by M123-dev** [comment]
For caching we can use [flutter_cache_manager](https://pub.dev/packages/flutter_cache_manager) then we don't have to implement a db or something.

**Comment by AmanNegi** [comment]
Yes using flutter_cache_manager is the right way to go. I can help you implement this.
