### ISSUE TITLE
Meassurement charts rounding

### ISSUE THREAD

**Issue by eyJhb** [wger-project/flutter#695]
## Steps to Reproduce

1. Add two weigh in e.g. 79.4 and 79.1
2. Refresh chart
3. Hopefully see rounding error?

**Expected results:** 
I would expect it to not write `79.39999999999999`, and instead just do `79.40`.

**Actual results:** 
![Image](https://github.com/user-attachments/assets/a3fae36b-350f-4631-900d-d24b2698d5c6)

** Other **
I'm unsure if any of the improvements in #657 could cause it, or if it's just a preexisting thing.

**Comment by rolandgeider** [comment]
mhhh, could not reproduce this, even with other "weird" numbers

**Comment by eyJhb** [comment]
I could reproduce it even on the latest master branch w/ Flutter desktop. I think the issue occurs, if the weight measurements are within the same whole number, but just different decimals. I reproduced it on wger.de, using the latest master branch.

I've made a user you can test on on wger.de
Username: issue-695@wger.de
Password: <same as username>

:)

**Comment by Dieterbe** [comment]
> weird that this only seemed to trigger with some numbers

my guess is that the charting library uses doubles with one decimal over a long range, and many more decimals on a short range, so it just "happened to work" with the standard printing behavior, before.

thanks for the report and the fix!
