### ISSUE TITLE
Allow user to set and edit profile

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#71]
## Use case

Allow user to set and edit profile, most importantly email. 

## Proposal

When we implement the exercise crowdsourcing, users will need to have a verified email address. We need to allow users on the flutter app to set and change their profile and email. At the moment the actual user profile is available under `/api/v2/userprofile` while the email can't be accessed over the api. 

We should add a new endpoint, something like `/api/v2/user` which (at the moment) would return only the email, we might want to add other fields there in the future. There would be other special sub endpoints like `/api/v2/user/verify-email` which would send a verification email.

Allowing to edit the profile itself is something we will have to add as well when we add a calories calculator or allow users to set some avatar or such.

**Comment by pratikb2805** [comment]
@rolandgeider hey I am new to flutter and have developed some apps with it.
Should I work on this?

**Comment by rolandgeider** [comment]
Hi, sure! I'll edit this issue tomorrow or so with a bit more infos on what needs to be done on the flutter and the backend side (which would be my tasks)

**Comment by rolandgeider** [comment]
have updated the description. Since you need a backend for this to work, write me an email and I can give you a user on the test server

**Comment by pratikb2805** [comment]
@rolandgeider  Thanks, I will get started on this.

**Comment by rolandgeider** [comment]
This was implemented in the meantime, closing
