### ISSUE TITLE
Add ingredient images

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#78]
## Use case

Seeing the image when logging or searching for a product would be really useful and comfortable for the user (can see the brand, etc. )

## Proposal

Add images for the ingredients, there is already a branch in the backend that retrieves them if none is known locally, but we need to think on how to make retrieving them more performant. 

https://github.com/wger-project/wger/tree/feature/ingredient-images
https://github.com/wger-project/wger/issues/653

**Comment by Coffiie** [comment]
Hello,
I see you have lots of good first issues open and would like to contribute to them. @rolandgeider

**Comment by rolandgeider** [comment]
Hi @Coffiie ! Sure! Did you want to do this one?

**Comment by Coffiie** [comment]
Sure, please assign this to me and I can begin

**Comment by rolandgeider** [comment]
It's yours!

Note that you need the branch for the backend to return the images. Do you want to setup a local docker instance? I could setup a test server the next days otherwise

**Comment by Coffiie** [comment]
Hmm, I have no idea how docker works... but if you think it'd be easy then I can give it a try

**Comment by rolandgeider** [comment]
We can try :)

1) First clone the web application (https://github.com/wger-project/wger) somewhere, leave master for now

2) Start the docker container, you should be able to open localhost:8000 on the browser. 
```
docker run -ti  \
  -v /path/to/your/wger/checkout:/home/wger/src \
  --name wger.devel \
  --publish 8000:8000 wger/devel
```
if you use windows I had problems with `-v` use this instead `--mount type=bind,source='"C:\path\to your\checkout"',target=/home/wger/src`

3) Load the ingredient data with `docker exec wger.devel wger load-online-fixtures`.

4) Now checkout the `feature/ingredient-images` branch and run the database migrations with `docker exec wger.devel python3 manage.py migrate`

You can e.g. go to nutrition > ingredients and click on one or you can also use the search bar The way this still works is that if an ingredient has no images locally, it retrieves them and that's a process that needs 2 API calls per image, so specially for the autocompleter, it can take some time (but that's a backend problem). The API response is here `/api/v2/ingredient/`
