### ISSUE TITLE
Use flutter_lints package

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#86]
From https://flutter.dev/docs/release/breaking-changes/flutter-lints-package  

> The package:flutter_lints defines the latest set of recommended lints that encourage good coding practices for Flutter apps, packages, and plugins. Projects created with flutter create using Flutter version 2.3.0-12.0.pre or newer are already enabled to use the latest set of recommended lints. Projects created prior to that version can upgrade to it with the instructions in this guide.

Since this project was created before that package was available, we need to migrate manually. Note that at the moment the app can't be build with flutter 2.5 due to https://github.com/google/charts/issues/678

**Comment by M123-dev** [comment]
Maybe this help: https://github.com/google/charts/issues/678#issuecomment-917163703

**Comment by rolandgeider** [comment]
I saw the workaround, I would say we can use it while working e.g. on this issue, but I would prefer not to commit to master

**Comment by M123-dev** [comment]
I can do this in the next days, it shouldn't take that long

**Comment by rolandgeider** [comment]
That would be great. There's no hurry, I mainly opened the issue so I don't forget about it

**Comment by Vikkybliz** [comment]
I can add the flutter_lint @rolandgeider should specify the rules you want there

**Comment by rolandgeider** [comment]
I would say that we keep the rules as similar to the current ones as possible, we can always tweak them in the future

**Comment by M123-dev** [comment]
@rolandgeider I started migrating. Just using `flutter_lints` causes 800 problems in the analyzer. If its okay with you I will change some logical linting rules so that we don't have to rewrite everything

**Comment by rolandgeider** [comment]
uff, are the new default rules so hard? but sure, tweak them as much as you think

**Comment by M123-dev** [comment]
After applying some basic ones it got even worse, I am about to fix some important ones but I' ll postpone some of them that should definitely be changed in the future to a follow up PR
