### ISSUE TITLE
Add Hebrew Translation To Wger

### ISSUE THREAD

**Issue by TomerPacific** [wger-project/flutter#88]
## Use case
Allow Hebrew speaking users to use the application
## Proposal

As part of the many languages detailed in the translation listed [here](https://hosted.weblate.org/engage/wger/), I would like to suggest the addition of Hebrew.

Willing to help out with the translations.

**Comment by rolandgeider** [comment]
Hi! For the mobile application you should be able to add a new language directly on weblate, for the regular web application this is something that I need to do manually. If this doesn't work, just ping me

If you start translating I'm guessing we will have a couple of places where the application breaks or doesn't look good when using a right-to-left language

**Comment by TomerPacific** [comment]
@rolandgeider, [added Hebrew language for the mobile application on Weblate](https://hosted.weblate.org/projects/wger/mobile/he/).

**Comment by rolandgeider** [comment]
Awesome! Thanks a lot

**Comment by TomerPacific** [comment]
@rolandgeider , I have done about 90% of the strings translations and there are a few I'd like to consult with you:

- kCal
- kJ
- RiR
- Wger

The above mentioned words do not have a direct translation in Hebrew, so what would you like done?
For example, would you like me to just write Wger in Hebrew? Or translate RiR directly/use the same abbreviation?

**Comment by rolandgeider** [comment]
would it look weird to leave "wger" with latin letters? I think the name is only shown in the about dialog, but do whatever you think is more natural. The units are mostly (only?) used next to numbers or in a chart so it's also probably alright to leave them

And as for RiR, if there is an existing translation for it, then we should use that one. If not or if you are unsure, then just leave RiR (in German for example we also don't translate it)

**Comment by TomerPacific** [comment]
@rolandgeider, I have completed the translation for the mobile application. Since Hebrew is a language which has a he/she change for verbs, in some places I have opted to refer to both genders and in others were it would be a lengthier sentence I have either used the male version or the plural male version.

**Comment by rolandgeider** [comment]
thanks! Weblate should commit the changes in the next hours.

I'm closing this issue, if there's something else broken or anything we can reopen it or make a new one
